version: "3"
services:
    app:
        image: dirui/mrpp-app:latest
        container_name: mrpp-app
        ports:
            - "80:80"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    db:
        image: dirui/mrpp-db:latest
        container_name: mrpp-db
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8015:80
        environment:
            - MYSQL_ROOT_PASSWORD=root
        depends_on:
            - db
volumes:
    db-data:

