version: "3"
services:
    app:
        depends_on:
            - db  
        restart: always
        build:
            context: ..
            dockerfile: ./Dockerfile-app
        container_name: local-mrpp-app
        networks:
            - proxy
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            - "traefik.http.routers.t-mrpp-secure.entrypoints=websecure"
            - "traefik.http.routers.t-mrpp-secure.rule=Host(`t.mrpp.com`)" 
            - "traefik.http.routers.t-mrpp-secure.middlewares=test-compress@file"
            - "traefik.http.routers.api-mrpp-secure.entrypoints=websecure"
            - "traefik.http.routers.api-mrpp-secure.rule=Host(`api.mrpp.com`)"
            - "traefik.http.routers.api-mrpp-secure.middlewares=test-compress@file"    
            - "traefik.http.routers.cfg-mrpp-secure.entrypoints=websecure"
            - "traefik.http.routers.cfg-mrpp-secure.rule=Host(`cfg.mrpp.com`)"  
            - "traefik.http.routers.cfg-mrpp-secure.middlewares=test-compress@file"  
            - "traefik.http.routers.wx-mrpp-secure.entrypoints=websecure"
            - "traefik.http.routers.wx-mrpp-secure.rule=Host(`wx.mrpp.com`)"  
            - "traefik.http.routers.wx-mrpp-secure.middlewares=test-compress@file"   
            - "traefik.http.routers.app-mrpp-secure.entrypoints=websecure"
            - "traefik.http.routers.app-mrpp-secure.rule=Host(`app.mrpp.com`)"   
            - "traefik.http.routers.app-mrpp-secure.middlewares=test-compress@file"
            - "traefik.http.routers.admin-mrpp-secure.entrypoints=websecure"
            - "traefik.http.routers.admin-mrpp-secure.rule=Host(`admin.mrpp.com`)"  
            - "traefik.http.routers.admin-mrpp-secure.middlewares=test-compress@file"   
        volumes:
            - ../..:/var/www/html
    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        restart: always
        environment:
            - WORDPRESS_DB_HOST=db:3306
            - WORDPRESS_DB_USER=wordpress
            - WORDPRESS_DB_PASSWORD=w0rdp2ess
            - WORDPRESS_DB_NAME=wordpress
        volumes:
            - ../../../wordpress:/var/www/html
        networks:
            - proxy
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            - "traefik.http.routers.wordpress-4mr-secure.entrypoints=websecure"
            - "traefik.http.routers.wordpress-4mr-secure.rule=Host(`wordpress.4mr.cn`)" 
            - "traefik.http.routers.wordpress-4mr-secure.middlewares=test-compress@file"
            - "traefik.http.routers.hololens2-secure.entrypoints=websecure"
            - "traefik.http.routers.hololens2-secure.rule=Host(`hololens2.cn`)" 
            - "traefik.http.routers.hololens2-secure.middlewares=test-compress@file"
            - "traefik.http.routers.www-hololens2-secure.entrypoints=websecure"
            - "traefik.http.routers.www-hololens2-secure.rule=Host(`www.hololens2.cn`)" 
            - "traefik.http.routers.www-hololens2-secure.middlewares=test-compress@file"
            - "traefik.http.routers.u7gm-secure.entrypoints=websecure"
            - "traefik.http.routers.u7gm-secure.rule=Host(`u7gm.com`)" 
            - "traefik.http.routers.u7gm-secure.middlewares=test-compress@file"
            - "traefik.http.routers.www-u7gm-secure.entrypoints=websecure"
            - "traefik.http.routers.www-u7gm-secure.rule=Host(`www.u7gm.com`)" 
            - "traefik.http.routers.www-u7gm-secure.middlewares=test-compress@file"
            - "traefik.http.routers.bjb-u7gm-secure.entrypoints=websecure"
            - "traefik.http.routers.bjb-u7gm-secure.rule=Host(`bjb.u7gm.com`)" 
            - "traefik.http.routers.bjb-u7gm-secure.middlewares=test-compress@file"
            - "traefik.http.routers.bujiaban-secure.entrypoints=websecure"
            - "traefik.http.routers.bujiaban-secure.rule=Host(`bujiaban.com`)" 
            - "traefik.http.routers.bujiaban-secure.middlewares=test-compress@file"
            - "traefik.http.routers.www-bujiaban-secure.entrypoints=websecure"
            - "traefik.http.routers.www-bujiaban-secure.rule=Host(`www.bujiaban.com`)" 
            - "traefik.http.routers.www-bujiaban-secure.middlewares=test-compress@file"
    db:
        build:
            context: ..
            dockerfile: ./Dockerfile-db
        container_name: local-mrpp-db
        restart: always
        volumes:
            - sql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=Setup2021
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=w0rdp2ess
        
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        networks:
            - proxy
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            - "traefik.http.routers.phpmyadmin-secure.entrypoints=websecure"
            - "traefik.http.routers.phpmyadmin-secure.rule=Host(`phpmyadmin.4mr.cn`)" 
        environment:
            - MYSQL_ROOT_PASSWORD=Setup2021
        depends_on:
            - db
        restart: always
volumes:
    sql-data:
networks:
    proxy:
      external: true

